### Teste de Sucesso - CEP válido
POST http://localhost:8081/consulta-tempo
Accept: application/json

{
  "cep": "06465135"
}

### Teste de Falha - CEP inválido
POST http://localhost:8081/consulta-tempo
Accept: application/json

{
  "cep": "12345-678"
}

### Teste de Falha - CEP não encontrado
POST http://localhost:8081/consulta-tempo
Accept: application/json

{
  "cep": "12345678"
}
