services:
  servicea:
    image: myapp/servicea:latest 
    build: 
      context: ./servicea
      dockerfile: Dockerfile
    container_name: servicea
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - PORT=8080
      - URL_CONSULTA=http://serviceb:8081
      - URL_ZIPKIN=http://zipkin:9411/api/v2/spans
      - SERVICE_NAME=service-a

  serviceb:
    image: myapp/serviceb:latest 
    build: 
      context: ./serviceb
      dockerfile: Dockerfile
    container_name: serviceb
    ports:
      - "8081:8081"
    networks:
      - app_network
    environment:
      - PORT=8081
      - URL_CEP=https://viacep.com.br/ws
      - URL_TEMPO=https://api.weatherapi.com/v1
      - API_KEY_TEMPO=3baa5b20172b4baf91c185158251003
      - URL_ZIPKIN=http://zipkin:9411/api/v2/spans
      - SERVICE_NAME=service-b

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app_network
    environment:
      - STORAGE_TYPE=mem

networks:
  app_network:
    driver: bridge
