// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/consulta-tempo": {
            "post": {
                "description": "Consulta temperatura por cidade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Labs-Two"
                ],
                "summary": "Consulta Temperatura",
                "parameters": [
                    {
                        "description": "City Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/labs-two-service-b_internal_entities.TempoRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/labs-two-service-b_internal_entities.TempoDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/labs-two-service-b_internal_entities.CustomErrors"
                        }
                    },
                    "422": {
                        "description": "Invalid Zipcode",
                        "schema": {
                            "$ref": "#/definitions/labs-two-service-b_internal_entities.CustomErrors"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "labs-two-service-b_internal_entities.Condition": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "number"
                },
                "icon": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "labs-two-service-b_internal_entities.Current": {
            "type": "object",
            "properties": {
                "cloud": {
                    "type": "number"
                },
                "condition": {
                    "$ref": "#/definitions/labs-two-service-b_internal_entities.Condition"
                },
                "dewpoint_c": {
                    "type": "number"
                },
                "dewpoint_f": {
                    "type": "number"
                },
                "feelslike_c": {
                    "type": "number"
                },
                "feelslike_f": {
                    "type": "number"
                },
                "gust_kph": {
                    "type": "number"
                },
                "gust_mph": {
                    "type": "number"
                },
                "heatindex_c": {
                    "type": "number"
                },
                "heatindex_f": {
                    "type": "number"
                },
                "humidity": {
                    "type": "number"
                },
                "is_day": {
                    "type": "number"
                },
                "last_updated": {
                    "type": "string"
                },
                "last_updated_epoch": {
                    "type": "integer"
                },
                "precip_in": {
                    "type": "number"
                },
                "precip_mm": {
                    "type": "number"
                },
                "pressure_in": {
                    "type": "number"
                },
                "pressure_mb": {
                    "type": "number"
                },
                "temp_c": {
                    "type": "number"
                },
                "temp_f": {
                    "type": "number"
                },
                "uv": {
                    "type": "number"
                },
                "vis_km": {
                    "type": "number"
                },
                "vis_miles": {
                    "type": "number"
                },
                "wind_degree": {
                    "type": "number"
                },
                "wind_dir": {
                    "type": "string"
                },
                "wind_kph": {
                    "type": "number"
                },
                "wind_mph": {
                    "type": "number"
                },
                "windchill_c": {
                    "type": "number"
                },
                "windchill_f": {
                    "type": "number"
                }
            }
        },
        "labs-two-service-b_internal_entities.CustomErrors": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "labs-two-service-b_internal_entities.Location": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "localtime": {
                    "type": "string"
                },
                "localtime_epoch": {
                    "type": "integer"
                },
                "lon": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "tz_id": {
                    "type": "string"
                }
            }
        },
        "labs-two-service-b_internal_entities.TempoDto": {
            "type": "object",
            "properties": {
                "current": {
                    "$ref": "#/definitions/labs-two-service-b_internal_entities.Current"
                },
                "location": {
                    "$ref": "#/definitions/labs-two-service-b_internal_entities.Location"
                }
            }
        },
        "labs-two-service-b_internal_entities.TempoRequestDto": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Consulta Tempo",
	Description:      "Consulta Temperaturas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
