definitions:
  labs-two-service-b_internal_entities.Condition:
    properties:
      code:
        type: number
      icon:
        type: string
      text:
        type: string
    type: object
  labs-two-service-b_internal_entities.Current:
    properties:
      cloud:
        type: number
      condition:
        $ref: '#/definitions/labs-two-service-b_internal_entities.Condition'
      dewpoint_c:
        type: number
      dewpoint_f:
        type: number
      feelslike_c:
        type: number
      feelslike_f:
        type: number
      gust_kph:
        type: number
      gust_mph:
        type: number
      heatindex_c:
        type: number
      heatindex_f:
        type: number
      humidity:
        type: number
      is_day:
        type: number
      last_updated:
        type: string
      last_updated_epoch:
        type: integer
      precip_in:
        type: number
      precip_mm:
        type: number
      pressure_in:
        type: number
      pressure_mb:
        type: number
      temp_c:
        type: number
      temp_f:
        type: number
      uv:
        type: number
      vis_km:
        type: number
      vis_miles:
        type: number
      wind_degree:
        type: number
      wind_dir:
        type: string
      wind_kph:
        type: number
      wind_mph:
        type: number
      windchill_c:
        type: number
      windchill_f:
        type: number
    type: object
  labs-two-service-b_internal_entities.CustomErrors:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  labs-two-service-b_internal_entities.Location:
    properties:
      country:
        type: string
      lat:
        type: number
      localtime:
        type: string
      localtime_epoch:
        type: integer
      lon:
        type: number
      name:
        type: string
      region:
        type: string
      tz_id:
        type: string
    type: object
  labs-two-service-b_internal_entities.TempoDto:
    properties:
      current:
        $ref: '#/definitions/labs-two-service-b_internal_entities.Current'
      location:
        $ref: '#/definitions/labs-two-service-b_internal_entities.Location'
    type: object
  labs-two-service-b_internal_entities.TempoRequestDto:
    properties:
      location:
        type: string
    type: object
info:
  contact: {}
  description: Consulta Temperaturas
  title: Consulta Tempo
  version: "1.0"
paths:
  /consulta-tempo:
    post:
      consumes:
      - application/json
      description: Consulta temperatura por cidade
      parameters:
      - description: City Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/labs-two-service-b_internal_entities.TempoRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/labs-two-service-b_internal_entities.TempoDto'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/labs-two-service-b_internal_entities.CustomErrors'
        "422":
          description: Invalid Zipcode
          schema:
            $ref: '#/definitions/labs-two-service-b_internal_entities.CustomErrors'
      summary: Consulta Temperatura
      tags:
      - Labs-Two
swagger: "2.0"
