basePath: /
definitions:
  labs-two-service-a_internal_entities.CepRequestDto:
    properties:
      cep:
        type: string
    type: object
  labs-two-service-a_internal_entities.CustomErrors:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  labs-two-service-a_internal_entities.TempoResponseDto:
    properties:
      city:
        type: string
      temp_C:
        type: number
      temp_F:
        type: number
      temp_K:
        type: number
    type: object
info:
  contact: {}
  description: Tudo Azul Temperaturas
  title: Consulta CEP
  version: "1.0"
paths:
  /consulta-cep:
    post:
      consumes:
      - application/json
      description: Consulta dados do CEP fornecido via JSON no corpo da requisição
      parameters:
      - description: CEP Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/labs-two-service-a_internal_entities.CepRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/labs-two-service-a_internal_entities.TempoResponseDto'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/labs-two-service-a_internal_entities.CustomErrors'
        "422":
          description: Invalid Zipcode
          schema:
            $ref: '#/definitions/labs-two-service-a_internal_entities.CustomErrors'
      summary: Consulta CEP
      tags:
      - Labs-Two
swagger: "2.0"
