// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"labs-two-service-b/config"
	"labs-two-service-b/internal/infra/services"
	"labs-two-service-b/internal/infra/tracing"
	"labs-two-service-b/internal/infra/web"
	"labs-two-service-b/internal/usecases"
)

import (
	_ "labs-two-service-b/docs"
)

// Injectors from wire.go:

func NewConfig() *config.AppSettings {
	appSettings := config.ProvideConfig()
	return appSettings
}

func NewGetTempUseCase() *usecases.GetTempoUseCase {
	appSettings := config.ProvideConfig()
	httpClient := services.NewHttpClient()
	serviceTempo := services.NewServiceTempo(httpClient, appSettings)
	tracingConfig := tracing.ProvideTracingConfig(appSettings)
	tracingProvider := tracing.ProvideTracingProvider(tracingConfig)
	getTempoUseCase := usecases.NewGetTempoUseCase(appSettings, serviceTempo, tracingProvider)
	return getTempoUseCase
}

func NewGetTempoHandler() *web.GetTempoHandler {
	appSettings := config.ProvideConfig()
	httpClient := services.NewHttpClient()
	serviceTempo := services.NewServiceTempo(httpClient, appSettings)
	tracingConfig := tracing.ProvideTracingConfig(appSettings)
	tracingProvider := tracing.ProvideTracingProvider(tracingConfig)
	getTempoUseCase := usecases.NewGetTempoUseCase(appSettings, serviceTempo, tracingProvider)
	getTempoHandler := web.NewGetCepHandler(appSettings, getTempoUseCase, serviceTempo, tracingProvider)
	return getTempoHandler
}

func InitializeTracing() (*tracing.TracingProvider, func()) {
	appSettings := config.ProvideConfig()
	tracingConfig := tracing.ProvideTracingConfig(appSettings)
	tracingProvider, cleanup := tracing.ProvideTracingProviderWithCleanup(tracingConfig)
	return tracingProvider, func() {
		cleanup()
	}
}

// wire.go:

var ProviderConfig = wire.NewSet(config.ProvideConfig)

var ProviderHttpClient = wire.NewSet(services.NewHttpClient)

var ProviderTempo = wire.NewSet(services.NewServiceTempo, wire.Bind(new(services.ServiceTempoInterface), new(*services.ServiceTempo)))

var ProviderTracingForHandler = wire.NewSet(tracing.ProvideTracingConfig, tracing.ProvideTracingProvider)

var ProviderTracingWithCleanup = wire.NewSet(tracing.ProvideTracingConfig, tracing.ProvideTracingProviderWithCleanup)

var ProviderGlobal = wire.NewSet(
	ProviderHttpClient,
	ProviderConfig,
	ProviderTempo,
	ProviderTracingForHandler,
)

var ProviderUseCase = wire.NewSet(usecases.NewGetTempoUseCase, wire.Bind(new(usecases.GetTempoUseCaseInterface), new(*usecases.GetTempoUseCase)))

var ProviderHandler = wire.NewSet(web.NewGetCepHandler)
